name: Generate Podcast Audio
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Butuh versi 3.10 ke atas buat Gradio
      - name: Install Gradio Client
        run: pip install gradio_client
      - name: Run Audio Generator
        run: python main.py
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: hasil-podcast-chatterbox-vibe
          path: podcast_output/
          
